Repository webfrontier-intern-20231002-20231031/todo-team-b, pull requests merged in 2023-11, with the labels that each got.

#89 ユーザテーブルの作成、ログインAPI、ユーザ登録APIの実装
  practical-fastapi/migration/env.py
  practical-fastapi/migration/versions/ca6e104db80f_.py
  practical-fastapi/migration/versions/e59f04331c0f_.py
  practical-fastapi/migration/versions/f1d49bc902f0_.py
  practical-fastapi/migration/versions/f6fff35b7139_.py
  practical-fastapi/src/api/v1/user.py
  practical-fastapi/src/app/router.py
  practical-fastapi/src/crud/user.py
  practical-fastapi/src/models/user.py
  practical-fastapi/src/schemas/schema.py
  practical-fastapi/マイグレーション作業ログ.md
Labels: FastAPI

#92 navbar＆ページ遷移実装
  front/app/Compornents/Header.tsx
  front/app/Tags/page.tsx
  front/app/TodoPOST/page.tsx
  front/app/page.tsx
  front/package-lock.json
  front/package.json
  front/tailwind.config.ts
Labels: Next.js

#97 Poetry.lockの編集
  practical-fastapi/.tool-versions
  practical-fastapi/poetry.lock
  practical-fastapi/pyproject.toml
  practical-fastapi/src/models/user.py
  practical-fastapi/src/test/conftest.py
Labels: Jenkins

#99 Todoテーブル実装
  front/app/Compornents/Header.tsx
  front/app/Compornents/TableCompornents/TodoGETAll.tsx
  front/app/page.tsx
Labels: Next.js

#101 手動テストまでのJenkinsの設定完了
  Jenkins/Jenkinsfile
  Jenkins/Jenkins作業ログ.md
  Jenkins/SETJenkins.md
Labels: Jenkins

#103 TodoDELETE実装
  front/app/Compornents/Header.tsx
  front/app/Compornents/TableCompornents/TodoGETAll.tsx
Labels: Next.js

#104 Userテーブルに対する正常処理のテストコード作成
  Jenkins/Jenkins作業ログ.md
  Jenkins/SETJenkins.md
  practical-fastapi/src/test/conftest.py
  practical-fastapi/src/test/test_user.py
Labels: FastAPI

#106 TodoUPDATE実装
  front/app/Compornents/TableCompornents/TodoGETAll.tsx
  front/app/api/TodoPUTDetail/[id]/route.ts
Labels: Next.js

#107 Make login page mizuno 1107
  front/app/Compornents/LoginCompornents/Login.tsx
  front/app/Login/page.tsx
  front/app/api/Login/route.ts
  practical-fastapi/migration/versions/cf796608283f_postgres_create_todo_table.py
  practical-fastapi/src/logging.json
Labels: Next.js

#108 ユーザテーブルに対するエラーハンドリングテストコードの実装
  practical-fastapi/src/test/test_user.py
Labels: FastAPI

#109 リモートサーバのJenkinsでのテストに成功
  Jenkins/Dockerfile
  Jenkins/Jenkinsfile
Labels: Jenkins

#110 ファイルの配置を変更
  Jenkins/Dockerfile
  Jenkins/Jenkins作業ログ.md
  Jenkins/requirements.txt
Labels: Jenkins

#111 TodoPOST機能の実装
  front/app/Compornents/Header.tsx
  front/app/api/TodoPOST/route.ts
  front/app/api/TodoPUTTag/route.ts
Labels: Next.js

#118 Make add jwt mizuno 1110
  front/.gitignore
  front/app/Compornents/LoginCompornents/Login.tsx
  front/app/Login/page.tsx
  front/app/api/.env.template
  front/app/api/Login/.env.template
  front/app/api/Login/route.ts
  front/app/api/TodoGETAll/route.ts
  front/app/api/auth.ts
  front/package-lock.json
  front/package.json
Labels: Next.js

#119 Jenkinsとslack,githubとの結び付け
  Jenkins/Jenkinsfile
  Jenkins/Jenkins作業ログ.md
Labels: Jenkins

#120 各apiにjwt検証機能を追加
  front/app/api/Login/route.ts
  front/app/api/TagDELETE/[id]/route.ts
  front/app/api/TagGETAll/route.ts
  front/app/api/TagPOST/route.ts
  front/app/api/TodoDELETE/[id]/route.ts
  front/app/api/TodoGETById/[id]/route.ts
  front/app/api/TodoPUTCompleted/[id]/route.ts
  front/app/api/TodoPUTDetail/[id]/route.ts
  front/app/api/TodoPUTTag/route.ts
Labels: Next.js

#122 作業ログの追加とTodoテーブルに対するエラーハンドリングテストコードの一例を追加
  Jenkins/Jenkins作業ログ.md
  Jenkins/SETJenkins.md
  practical-fastapi/src/crud/todo.py
  practical-fastapi/src/test/test_todos.py
  practical-fastapi/マイグレーション作業ログ.md
Labels: Jenkins

#123 トークン切れ時にログイン画面へ遷移させる機能を追加
  front/app/Compornents/Header.tsx
  front/app/Compornents/TableCompornents/TodoGETAll.tsx
  front/app/api/Login/route.ts
  front/app/api/TodoPOST/route.ts
Labels: Next.js

#124 検索ソート機能実装
  front/app/Compornents/TableCompornents/TodoGETAll.tsx
  front/app/page.tsx
Labels: Next.js

#125 Jenkinsの並列処理実行と作業ログの追加
  Jenkins/Jenkinsfile
  Jenkins/Jenkins作業ログ.md
  practical-fastapi/pytest.ini
  practical-fastapi/src/test/test_tags.py
  practical-fastapi/src/test/test_todos.py
  practical-fastapi/src/test/test_user.py
Labels: Jenkins

#126 Design rework ono 1114
  front/app/Compornents/Header.tsx
  front/app/Compornents/TableCompornents/TodoGETAll.tsx
Labels: Next.js

#128 作業ログの更新
  Jenkins/Jenkins作業ログ.md
Labels: Jenkins
